### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by danielo515** [Drugoy/Autohotkey-scripts-.ahk#10]
Hello I would love to know which license are you using. 
I'm particularly interested in extending moveout functionality to fit my needs. Once it is completed and stable I would like to release it and I need to know how to give you credit properly. Please consider including a license.md file in the repository.

Thanks in advance.

**Comment by Drugoy** [comment]
MoveOut was written by <a href="http://www.donationcoder.com/Software/Skrommel/index.html#MoveOut">Skrommel</a> (as credits say).
If you are interested in any of my scripts - none of them are licensed, since I neither recognize copyright, nor I recognize authorship over ideas or the code.
Feel free to use my scripts however you like.
I'll be glad if you'd give me some credit for them, but that's not mandatory.

Also, I'd gladly accept any patches providing improvements to my scripts.
