### ISSUE TITLE
[MasterScript.ahk] NoTrayOrphans() is not compatible with Windows 10? 

### ISSUE THREAD

**Issue by war59312** [Drugoy/Autohotkey-scripts-.ahk#13]
Hi,

It seems NoTrayOrphans does NOT work on Windows 10.

It does nothing. Old icons still there. No errors or anything though.

> 1.) Windows 10 x64 Version 1607 Build 14393.82
> 
> 2.)  AutoHotkey v1.1.24.01 - August 2, 2016

Thanks,

Will

**Comment by Drugoy** [comment]
Hi Will,

First of all - sorry, but I don't have a PC with Win10 to test that (I'm using Windows 7 SP1).

Thing is that NoTrayOrphans() is not my function/lib, the latest version of MasterScript.ahk (that was uploaded to this repository) doesn't even use it, because I've found a better and simpler way to achieve the same result.
Unfortunately, MasterScript.ahk is on the stage of a quite big rewrite happening outside of repository: I can't merge the changes yet because I've broken a few things and some stuff is not yet finished (all the problems are generally solvable, it's just I procrastinate fixing them).

As for the issue of manipulation over Win10's tray bar - I could write a simple set of 2 test scripts that I'd need you to run and tell me the result.

**Comment by war59312** [comment]
I see that now. What's the simpler way? Got a link? Thanks.

OK, sure. Will be happy to help test.

**Comment by Drugoy** [comment]
Sorry, I was confused: I removed NoTrayOrphans() as it was incompatible with x64, not because I've found a better replacement for it.
Then I've found <a href="https://autohotkey.com/boards/viewtopic.php?f=6&t=1229">a similar lib</a> that works file with x64 and that I thought would not only replace NoTrayOrphans() for me, but would also let MasterScript hide/restore tray icons of other scripts (a feature I wanted for quite some long time).

But then I found out that:
1. it works only if they are alive, it doesn't work with tray orphans.
2. its hide() function works in such a way that the hidden icon still has a space in tray reserved for it, which makes the whole point of hiding the icon kind of useless.

So I just removed both NoTrayOrphans() and TrayIcon lib, as each had it's flaws.

I just forgot about all the details about all of that and to restore the above explained reasons to my decisions that I made some time ago - I now had to remember all that and also to search for some of those things.

Now it turns out that in fact the TrayIcon lib <a 
href="https://autohotkey.com/boards/viewtopic.php?p=92861#p92861">can be used</a> to kill orphans, which I found out just now because you pinged me and I needed to reply to you :)
Also, the author of that post mentions there that it works for him under W10x64, so there's no need for you to bother.

As for the 2nd flaw of TrayIcon (the inability to hide/restore other scripts' icons properly) - I found <a href="https://autohotkey.com/board/topic/65494-oneicon-tame-your-tray-menu/?p=516042#post_id_516042">a better solution</a> and that's what I had on my mind when I wrote the previous message.

**Comment by war59312** [comment]
I see, thank you very much. :)

No problem.

I'm not sure how to make use of that. I'm no AutoHotkey expert. Beginner at best.

Really just need something I can run to remove those orphans. Perhaps best for me to ask on their forums.

I very much appreciate you taking the time to respond and doing that research for me.

Thanks again!

**Comment by Drugoy** [comment]
Hey @war59312 
Check out new version.
It still may need some extra testing because the rewrite was quite big, so I need feedback.
Please, bear in mind that the newer version uses a different organization of settings, so compatibility with old settings files from older versions is broken, you'd better delete the old *settings.ini and let the script re-create a new one.
